CREATE TABLE DEPT(
DEPT_ID NUMBER(7) CONSTRAINT PK PRIMARY KEY, 
DEPT_NAME VARCHAR2(20)
);

DESC DEPT;

INSERT INTO DEPT VALUES (10,'ACCOUNTS');
--INSERT INTO DEPT VALUES (NULL,'ACCOUNTS');
INSERT INTO DEPT VALUES (20,'IT');
--INSERT INTO DEPT VALUES ('A1','IT');
INSERT INTO DEPT VALUES (30,'ACCOUNTS');

SELECT * FROM DEPT;