CREATE TABLE EMP_TABLE(
EMP_ID NUMBER(7) CONSTRAINT PKFOREMP PRIMARY KEY,
LAST_NAME VARCHAR2(25) NOT NULL,
FIRST_NAME VARCHAR2(25),
DEPT_ID NUMBER(7) CONSTRAINT FKFOREMP REFERENCES DEPT(DEPT_ID)
);

DESC EMP_TABLE;

INSERT INTO EMP_TABLE VALUES (101,'SAM','SUNDAR',10);
--INSERT INTO EMP_TABLE VALUES (101,'RAM','KRISHNA',20); PRIMARY KEY VIOLATION
--INSERT INTO EMP_TABLE VALUES (102,'GOPI',NULL,40); FOREIGN KEY VIOLATION NO SUCH FOREIGN KEY PRESENT
--INSERT INTO EMP_TABLE VALUES (103,NULL,'RAM',20); NOT NULL CONSTRAINT VIOLATION